/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:1741cadd-d1c6-4ae9-b9ab-f52ddfe8c145",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_LpGEXZHrW",
    "aws_user_pools_web_client_id": "6ddeh1teq2kvff2abrn4qdrvr5",
    "oauth": {
        "domain": "guguto-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://gugu.vercel.app/callback",
        "redirectSignOut": "https://gugu.vercel.app/callback",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
