/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:fc0666c8-5989-40ac-8d80-cd169f5cf46d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_l589PseB6",
    "aws_user_pools_web_client_id": "5df7phhc10uaijujhri1r5e5kb",
    "oauth": {
        "domain": "gugu-prod.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://gugu.vercel.app/callback/",
        "redirectSignOut": "https://gugu.vercel.app/callback/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
